COLORS_CONCORRENTI = {
    "C1": "red",
    "C2": "teal",
    "C3": "orange",
    "C4": "deep-purple",
    "C5": "light-green",
    "C6": "blue",
    "C7": "amber",
    "C8": "deep-orange",
    "C9": "light-blue",
    "C10": "green",
    "C11": "indigo",
    "C12": "lime",
    "C13": "pink",
    "C14": "purple",
    "C15": "cyan",
}
